<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
	  <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\app.ico" />
    <None Remove="Repository\repository.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="app.ico" />
    <Content Include="Images\app.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Repository\repository.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
	<ItemGroup>
		<Content Include="Profiles\*.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
    <Folder Include="Helpers\" />
    <Folder Include="Data\" />
    <Folder Include="Profiles\" />
    <Folder Include="Repository\Launchers\" />
    <Folder Include="Repository\Navigation\" />
    <Folder Include="Repository\GNSS\" />
    <Folder Include="Repository\Voice\" />
    <Folder Include="Repository\Players\" />
    <Folder Include="Resources\" />
    <Folder Include="Controls\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.ECS" Version="4.0.102" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

</Project>
